import os
import json
import re
import litellm
from datetime import datetime
from crewai import Crew, Task
from agents.strategist import create_strategist
from agents.copywriter import create_copywriter
from agents.art_director import create_art_director

MODEL_NAME = "groq/llama-3.3-70b-versatile"

def run_agency(chat_summary):
    marketing_lead = create_strategist()
    copywriter = create_copywriter()
    art_director = create_art_director()
    
    planning_task = Task(
        description=f"""
        Analyze the finalized campaign brief from this chat:
        {chat_summary}
        
        Act as a Chief Marketing Officer (CMO).
        Develop a world-class, multi-format content calendar. 
        You MUST assign a specific FORMAT for each piece of content. The mix MUST include:
        - "Reel/TikTok Video"
        - "Carousel Post"
        - "Static Image"
        
        For each day, define:
        1. Day, Time, and FORMAT.
        2. Funnel Stage (TOFU/MOFU/BOFU).
        3. Core Message & Psychological Trigger (e.g., FOMO, Social Proof).
        """,
        expected_output="A high-level CMO strategy mapping out the exact format and psychological trigger for every piece of content.",
        agent=marketing_lead
    )
    
    writing_task = Task(
        description="""
        Take the CMO's Content Calendar. 
        Write the EXACT, ready-to-publish copy. 
        
        CRITICAL FORMATTING RULES:
        1. If the format is "Reel/TikTok Video": Write a 2-column SCRIPT (Visuals: what we see | Audio: Voiceover/Text on screen). Include a caption with hashtags.
        2. If the format is "Carousel Post": Write the exact copy for Slide 1, Slide 2, Slide 3, etc., plus the main caption.
        3. If the format is "Static Image": Write a scroll-stopping caption with hooks and engaging text.
        """,
        expected_output="Fully fleshed-out scripts for videos, slide-by-slide copy for carousels, and captions for static posts.",
        agent=copywriter,
        context=[planning_task] 
    )

    visual_task = Task(
        description="""
        Take the content generated by the Copywriter.
        Write highly detailed 'Image Prompts' ready for Midjourney v6.
        
        For Videos/Reels: Write a prompt for the VIDEO THUMBNAIL.
        For Carousels: Write a prompt for the FIRST SLIDE (Cover).
        For Static: Write the prompt for the image.
        
        MIDJOURNEY V6 PROMPT RULES:
        Include camera angle, lens (e.g., 35mm, 85mm), lighting (cinematic, volumetric), and end with --ar 4:5 --style raw --v 6.0
        
        CRITICAL INSTRUCTION - OUTPUT FORMAT:
        You MUST output ONLY a valid JSON array of objects. All newlines MUST be escaped as \\n. DO NOT use actual line breaks inside strings.
        
        Each object must have EXACTLY these 4 keys:
        - "day": Day and Time.
        - "format": (e.g., "Reel Script", "Carousel", "Static Post").
        - "content": The full script, carousel slides, or caption. Use \\n for line breaks.
        - "prompt": The Midjourney v6 prompt for the thumbnail/image.
        
        Example format:
        [
          {
            "day": "Day 1 - 10:00 AM",
            "format": "Reel/TikTok Video",
            "content": "[Visual]: Fast zoom into a glowing screen.\\n[Audio]: Stop scrolling! Here is the secret...\\n\\nCaption: Join us now! #Event",
            "prompt": "A glowing futuristic screen in a dark room, neon cyan lighting, 35mm lens, cinematic depth of field --ar 9:16 --v 6.0"
          }
        ]
        """,
        expected_output="A strictly valid JSON array containing day, format, content (scripts/captions), and prompt for every piece.",
        agent=art_director,
        context=[writing_task] 
    )
    
    agency_crew = Crew(
        agents=[marketing_lead, copywriter, art_director],
        tasks=[planning_task, writing_task, visual_task],
        verbose=True
    )
    
    print("\n[Building the campaign...]")
    result = agency_crew.kickoff()
    
    raw_text = str(result)
    
    start_idx = raw_text.find('[')
    end_idx = raw_text.rfind(']')
    
    if start_idx != -1 and end_idx != -1:
        clean_json = raw_text[start_idx:end_idx+1]
    else:
        clean_json = raw_text
    
    try:
        campaign_data = json.loads(clean_json, strict=False)
        
        output_dir = "campaigns"
        os.makedirs(output_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{output_dir}/campaign_{timestamp}.json"
        
        with open(filename, "w", encoding="utf-8") as file:
            json.dump(campaign_data, file, ensure_ascii=False, indent=4)
            
        print(f"SUCCESS: Campaign saved locally to {filename}")
        return campaign_data
        
    except json.JSONDecodeError as e:
        print(f"[Error] Failed to parse JSON: {e}")
        return [{"day": "System Error", "format": "Error", "content": raw_text, "prompt": f"Failed to parse JSON formats. Text extracted: {clean_json[:100]}"}]